# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: request_cancel_all_orders.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'request_cancel_all_orders.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1frequest_cancel_all_orders.proto\x12\x03rti\"\x81\x03\n\x16RequestCancelAllOrders\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x02(\x05\x12\x12\n\x08user_msg\x18\x98\x8d\x08 \x03(\t\x12\x10\n\x06\x66\x63m_id\x18\x9d\xb3\t \x01(\t\x12\x0f\n\x05ib_id\x18\x9e\xb3\t \x01(\t\x12\x14\n\naccount_id\x18\x98\xb3\t \x01(\t\x12\x39\n\tuser_type\x18\xb4\xb3\t \x01(\x0e\x32$.rti.RequestCancelAllOrders.UserType\x12\x44\n\x0emanual_or_auto\x18\xd6\xb8\t \x01(\x0e\x32*.rti.RequestCancelAllOrders.OrderPlacement\"&\n\x0eOrderPlacement\x12\n\n\x06MANUAL\x10\x01\x12\x08\n\x04\x41UTO\x10\x02\"Z\n\x08UserType\x12\x13\n\x0fUSER_TYPE_ADMIN\x10\x00\x12\x11\n\rUSER_TYPE_FCM\x10\x01\x12\x10\n\x0cUSER_TYPE_IB\x10\x02\x12\x14\n\x10USER_TYPE_TRADER\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'request_cancel_all_orders_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTCANCELALLORDERS']._serialized_start=41
  _globals['_REQUESTCANCELALLORDERS']._serialized_end=426
  _globals['_REQUESTCANCELALLORDERS_ORDERPLACEMENT']._serialized_start=296
  _globals['_REQUESTCANCELALLORDERS_ORDERPLACEMENT']._serialized_end=334
  _globals['_REQUESTCANCELALLORDERS_USERTYPE']._serialized_start=336
  _globals['_REQUESTCANCELALLORDERS_USERTYPE']._serialized_end=426
# @@protoc_insertion_point(module_scope)
