# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: response_get_instrument_by_underlying_keys.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'response_get_instrument_by_underlying_keys.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0response_get_instrument_by_underlying_keys.proto\x12\x03rti\"\xb1\x01\n%ResponseGetInstrumentByUnderlyingKeys\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x02(\x05\x12\x12\n\x08user_msg\x18\x98\x8d\x08 \x03(\t\x12\x11\n\x07rp_code\x18\x9e\x8d\x08 \x03(\t\x12\x1b\n\x11underlying_symbol\x18\xa2\x95\x06 \x03(\t\x12\x12\n\x08\x65xchange\x18\x95\xdc\x06 \x03(\t\x12\x19\n\x0f\x65xpiration_date\x18\xe3\x8d\x06 \x03(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'response_get_instrument_by_underlying_keys_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESPONSEGETINSTRUMENTBYUNDERLYINGKEYS']._serialized_start=58
  _globals['_RESPONSEGETINSTRUMENTBYUNDERLYINGKEYS']._serialized_end=235
# @@protoc_insertion_point(module_scope)
